import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  prepareCompileDb,
  parseUnityIncludes,
  resolveUnityMember,
  expandUnityEntries
} from '../../../mcp/stdio/code-intel/compile-db.js';

const isWin = process.platform === 'win32';

// Produce a `file` value that, after wslToHost on the current platform,
// resolves under `dir`. On win32 we feed a WSL path so normalization is
// exercised; off win32 we feed the host path directly.
function wslish(dir, rel) {
  const abs = path.join(dir, rel).replace(/\\/g, '/');
  if (isWin) {
    const m = /^([A-Za-z]):(\/.*)$/.exec(abs);
    if (m) return `/mnt/${m[1].toLowerCase()}${m[2]}`;
  }
  return abs;
}

function hostAbs(dir, rel) {
  return path.join(dir, rel).replace(/\\/g, '/');
}

describe('parseUnityIncludes (pure)', () => {
  it('extracts quoted member sources, ignores angle-bracket includes', () => {
    const body = [
      '/* generated by CMake */',
      '#include "/mnt/c/x/engine/A.cpp"',
      '/* NOLINTNEXTLINE */',
      '  #include  "B.cpp"',
      '#include <vector>',
      '#include <some/system.h>'
    ].join('\n');
    expect(parseUnityIncludes(body)).toEqual(['/mnt/c/x/engine/A.cpp', 'B.cpp']);
  });

  it('returns [] for empty/non-string', () => {
    expect(parseUnityIncludes('')).toEqual([]);
    expect(parseUnityIncludes(undefined)).toEqual([]);
  });
});

describe('resolveUnityMember (pure, injectable exists)', () => {
  it('resolves an absolute WSL member to host path when it exists', () => {
    if (!isWin) return;
    const exists = (p) => p === 'C:/x/engine/A.cpp';
    expect(resolveUnityMember('/mnt/c/x/engine/A.cpp', 'C:/x/build/U', exists))
      .toBe('C:/x/engine/A.cpp');
  });

  it('resolves a dir-relative member against the unity dir', () => {
    const unityDir = '/repo/build/U';
    const exists = (p) => p === '/repo/build/U/B.cpp';
    expect(resolveUnityMember('B.cpp', unityDir, exists)).toBe('/repo/build/U/B.cpp');
  });

  it('returns null for non-C++ targets and missing files', () => {
    expect(resolveUnityMember('foo.h', '/d', () => true)).toBe(null);
    expect(resolveUnityMember('A.cpp', '/d', () => false)).toBe(null);
  });
});

describe('prepareCompileDb — unity expansion', () => {
  let repo;
  beforeEach(() => {
    repo = fs.mkdtempSync(path.join(os.tmpdir(), 'apg-unity-'));
  });
  afterEach(() => { try { fs.rmSync(repo, { recursive: true, force: true }); } catch {} });

  function writeFile(rel, content) {
    const p = path.join(repo, rel);
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, content);
  }
  function writeDb(rel, entries) {
    writeFile(rel, JSON.stringify(entries, null, 2));
  }

  it('expands ONE unity TU into its two real member sources', () => {
    // Real member sources on disk.
    writeFile('engine/console/Console.cpp', 'void a(){}\n');
    writeFile('engine/console/Commands.cpp', 'void b(){}\n');

    // Unity aggregate .cxx that #includes the two members (absolute WSL paths,
    // exactly like CMake emits).
    const unityRel = 'build/engine/console/CMakeFiles/engine_console.dir/Unity/unity_0_cxx.cxx';
    const unityBody = [
      '/* generated by CMake */',
      `#include "${wslish(repo, 'engine/console/Console.cpp')}"`,
      `#include "${wslish(repo, 'engine/console/Commands.cpp')}"`
    ].join('\n');
    writeFile(unityRel, unityBody);

    const buildDirWsl = wslish(repo, 'build');
    const unityFileWsl = wslish(repo, unityRel);
    writeDb('build/compile_commands.json', [
      {
        directory: buildDirWsl,
        file: unityFileWsl,
        command: `/usr/bin/c++ -DFOO -I${wslish(repo, 'engine')} -std=c++20 -o out.o -c ${unityFileWsl}`,
        output: 'out.o'
      }
    ]);

    const r = prepareCompileDb({ projectRoot: repo });
    expect(r.found).toBe(true);
    expect(r.unity).toBe(true);
    expect(r.unityExpanded).toBe(true);
    expect(r.expandedFrom).toBe(1);
    expect(r.expandedSources).toBe(2);
    expect(r.firstPartyCount).toBe(2);
    expect(r.diagnostics.some(d => d.code === 'unity_expanded')).toBe(true);
    expect(r.diagnostics.some(d => d.code === 'unity_build')).toBe(false);

    // Normalized DB contains the two member files, NOT the unity aggregate.
    const norm = JSON.parse(fs.readFileSync(r.normalizedPath, 'utf8'));
    const files = norm.map(e => e.file.replace(/\\/g, '/').toLowerCase());
    const consoleAbs = hostAbs(repo, 'engine/console/Console.cpp').toLowerCase();
    const commandsAbs = hostAbs(repo, 'engine/console/Commands.cpp').toLowerCase();
    expect(files).toContain(consoleAbs);
    expect(files).toContain(commandsAbs);
    expect(files.some(f => /unity_0_cxx\.cxx/.test(f))).toBe(false);

    // Synthesized entry keeps the unity flags, with the unity path swapped for
    // the member source, and no leftover internal bookkeeping / output.
    const consoleEntry = norm.find(e => e.file.replace(/\\/g, '/').toLowerCase() === consoleAbs);
    expect(consoleEntry.command).toMatch(/-DFOO/);
    expect(consoleEntry.command).toMatch(/-std=c\+\+20/);
    expect(consoleEntry.command).not.toMatch(/unity_0_cxx\.cxx/);
    expect(consoleEntry.command).toMatch(/Console\.cpp/);
    expect(consoleEntry.output).toBeUndefined();
    expect(Object.keys(consoleEntry).some(k => k.startsWith('__'))).toBe(false);
  });

  it('does NOT expand when the unity .cxx file is missing on disk', () => {
    // DB references a unity .cxx that was never written to disk.
    const buildDirWsl = wslish(repo, 'build');
    const unityFileWsl = wslish(repo, 'build/CMakeFiles/x.dir/Unity/unity_0_cxx.cxx');
    writeDb('build/compile_commands.json', [
      { directory: buildDirWsl, file: unityFileWsl, command: `c++ -c ${unityFileWsl}` }
    ]);

    const r = prepareCompileDb({ projectRoot: repo });
    expect(r.found).toBe(true);
    expect(r.unity).toBe(true);
    expect(r.unityExpanded).toBe(false);
    expect(r.expandedSources).toBe(0);
    // Keeps the not-ready unity_build diagnostic.
    expect(r.diagnostics.some(d => d.code === 'unity_build')).toBe(true);
    expect(r.diagnostics.some(d => d.code === 'unity_expanded')).toBe(false);
  });

  it('expandUnityEntries (pure, injectable io) ignores dep members and de-dupes', () => {
    const normalized = [
      {
        file: '/repo/build/U/unity_0_cxx.cxx'.replace('U', 'CMakeFiles/t.dir/Unity'),
        directory: '/repo/build',
        command: 'c++ -c /repo/build/CMakeFiles/t.dir/Unity/unity_0_cxx.cxx'
      }
    ];
    // Fix the unity path to actually match isUnityFile.
    normalized[0].file = '/repo/build/CMakeFiles/t.dir/Unity/unity_0_cxx.cxx';
    const body = [
      '#include "/repo/engine/A.cpp"',
      '#include "/repo/engine/A.cpp"',          // duplicate
      '#include "/repo/_deps/lib/B.cpp"'         // dep — excluded
    ].join('\n');
    const io = {
      exists: (p) => ['/repo/build/CMakeFiles/t.dir/Unity/unity_0_cxx.cxx', '/repo/engine/A.cpp', '/repo/_deps/lib/B.cpp'].includes(p),
      read: () => body
    };
    const { expanded, unityTuCount, expandedSources } = expandUnityEntries(normalized, '/repo', io);
    expect(unityTuCount).toBe(1);
    expect(expandedSources).toBe(1);
    expect(expanded.map(e => e.file)).toEqual(['/repo/engine/A.cpp']);
  });
});
