// ★ M2's OTHER HALF: state what was NOT modelled, not only how good the index is.
//
// Every TRUST line this repo emitted described EVIDENCE QUALITY — heuristic-only, coverage
// incomplete, index not ready, collection stale, fetch cap hit. All of them answer "how much do we
// trust what we indexed". None answered "what can this analysis not see at all", and a search for
// "not modelled" across mcp/ returned ZERO hits before this.
//
// The distinction matters at exactly one moment: an agent reading "NO CALLERS" and deciding whether
// a symbol is safe to delete. A stale index means "look again". An unmodelled construct means
// "looking again with the same tool will give the same wrong answer".
//
// ⚠ CLAIM CEILING, ASSERTED BELOW: this states a property of the ANALYSIS. It must never read as a
// claim that the queried symbol is affected by macros or conditional compilation — that would be a
// suspicion with no evidence behind it, attached to every C++ absence.
import { describe, it, expect } from 'vitest';
import { buildAbsenceTrustLine, constructCoverageClause } from '../../../mcp/stdio/query/lsp-evidence.js';
import { expectAbsentWithLiveMatcher } from '../../helpers/live-matcher.js';

describe('an absence claim names what the analysis structurally cannot see', () => {
  it('★ a C++ absence names indirection, macros and conditional compilation', async () => {
    const line = await buildAbsenceTrustLine({ noun: 'callers', language: 'cpp' });
    expect(line).toMatch(/NOT MODELLED/);
    expect(line, 'indirection').toMatch(/function pointers or std::function/);
    expect(line, 'macros').toMatch(/generated by macros/);
    expect(line, 'conditional compilation').toMatch(/excluded by conditional compilation/);
  });

  it('⛔ it names the limit that SURVIVES clangd — the non-obvious half', async () => {
    // Pointing an agent at code_intel_references does not escape this one: clangd resolves ONE
    // compile configuration, so a symbol used only inside an inactive #ifdef branch is invisible
    // to the strongest evidence tier we have. A caveat that only covered the heuristic tier would
    // send the reader to a tool that shares the blind spot.
    const line = await buildAbsenceTrustLine({ noun: 'callers', language: 'cpp' });
    expect(line).toMatch(/ONE compile configuration/);
    expect(line).toMatch(/invisible to BOTH tiers/);
  });

  it('⛔ CLAIM CEILING: it describes the analysis, never the queried symbol', async () => {
    const line = await buildAbsenceTrustLine({ noun: 'callers', language: 'cpp' });
    expect(line).toMatch(/NOT that this symbol is affected/);
  });

  it('⛔ a JavaScript absence carries NO construct clause — zero bytes, not a wall', () => {
    // The 445-byte warning wall this project already tore out was unconditional prose. A caveat
    // everyone skims protects nobody, so this one is paid for only where the constructs exist.
    expectAbsentWithLiveMatcher(
      /NOT MODELLED/,
      { forbidden: ' NOT MODELLED: calls through function pointers or std::function, calls generated by macros,',
        allowed: '' },
      constructCoverageClause('javascript'),
      'the clause is language-conditioned; a JS repo pays nothing for it',
    );
    expect(constructCoverageClause('typescript')).toBe('');
    expect(constructCoverageClause('python')).toBe('');
  });

  it('the C-family is recognised through the backend registry, not a parallel list', () => {
    // `c` aliases to `cpp` in code-intel/backends.js, so C gets the clause without a second list
    // here that could drift from the registry.
    expect(constructCoverageClause('c')).toMatch(/NOT MODELLED/);
    expect(constructCoverageClause('CPP')).toMatch(/NOT MODELLED/);
    // `c_cpp` is the resolver's family bucket (ingest/resolver.js:47-48) and is NOT a registry
    // alias — matched explicitly, because adding it to the alias map would change which backend
    // gets selected for those rows.
    expect(constructCoverageClause('c_cpp')).toMatch(/NOT MODELLED/);
  });

  it('an unknown or missing language adds nothing — fail closed, not fail loud', () => {
    expect(constructCoverageClause(null)).toBe('');
    expect(constructCoverageClause(undefined)).toBe('');
    expect(constructCoverageClause('')).toBe('');
    expect(constructCoverageClause('rust')).toBe('');
  });

  it('the base absence caveat is unchanged for every language', async () => {
    // Regression guard: the construct clause is ADDITIVE. The existing not-exhaustive caveat is
    // what routes an agent away from treating absence as proof, and it must survive.
    for (const language of [null, 'cpp', 'javascript']) {
      const line = await buildAbsenceTrustLine({ noun: 'callers', language });
      expect(line, `base caveat missing for ${language}`).toMatch(/absence is from the heuristic graph and is NOT exhaustive/);
    }
  });
});
